// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NerdStore.Vendas.Data;

namespace NerdStore.Vendas.Data.Migrations
{
    [DbContext(typeof(VendasContext))]
    partial class VendasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.MinhaSequencia", "'MinhaSequencia', '', '1000', '1', '', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NerdStore.Vendas.Domain.Entidades.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdPedido");

                    b.Property<Guid>("IdProduto");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Quantidade");

                    b.Property<decimal>("ValorUnitario");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("NerdStore.Vendas.Domain.Entidades.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEXT VALUE FOR MinhaSequencia");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<decimal>("Desconto");

                    b.Property<Guid>("IdCliente");

                    b.Property<Guid?>("IdVoucher");

                    b.Property<int>("PedidoStatus");

                    b.Property<decimal>("ValorTotal");

                    b.Property<bool>("VoucherUtilizado");

                    b.HasKey("Id");

                    b.HasIndex("IdVoucher");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("NerdStore.Vendas.Domain.Entidades.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DataCriacao");

                    b.Property<DateTime?>("DataUtilizacao");

                    b.Property<DateTime>("DataValidade");

                    b.Property<decimal?>("Percentual");

                    b.Property<int>("Quantidade");

                    b.Property<int>("TipoDescontoVoucher");

                    b.Property<bool>("Utilizado");

                    b.Property<decimal?>("ValorDesconto");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("NerdStore.Vendas.Domain.Entidades.ItemPedido", b =>
                {
                    b.HasOne("NerdStore.Vendas.Domain.Entidades.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdPedido");
                });

            modelBuilder.Entity("NerdStore.Vendas.Domain.Entidades.Pedido", b =>
                {
                    b.HasOne("NerdStore.Vendas.Domain.Entidades.Voucher", "Voucher")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdVoucher");
                });
#pragma warning restore 612, 618
        }
    }
}
